Product--Add_To_Inventory.md, Product--CREATE-InventoryList-SubCatalog.md, Product--DELETE-InventoryList-SubCatalog.md, Product--Export.md, Product--ItemDetails.md, Product--READ-InventoryList-SubCatalog.md, Product--SKU_autocomplete.md, Product--SearchCatalog-SubCatalog_and_Inventory.md, Product--UPDATE-InventoryList-SubCatalog.md
I'm still not sure on one or two of these, but this is my first pass changes to this.  [btw, I love working with version control and I love working in markdown]
=> first pass from product backend

Order--AddTracking.md, Order--Fees.md
Propose that we use the same structure combo for sku_id and quantity
that we have elsewhere and change the return to 204 since we aren't
returning any data.  And then just making explicit the success and
error status codes.
add_tracking_updates
=> proposing updates for add tracking

Order--AddTracking.md
Instead of sku, can we do order_line_items?  we could
include sku too if desired inside line_items.  Is this
any different or easier or harder for you?
tracking_req_change
=> adding tracking to required and line items now

Product--SearchCatalog-SubCatalog_and_Inventory.md
Amends Product--SearchCatalog-SubCatalog_and_Inventory response
Changes include
- adding items.name (used for item's title)
- identifying sort field keys/direction
=> Ammended Product--SearchCatalog-SubCatalog_and_Inventory

Product--ItemDetails.md
and fixed some indentation that was off.
I accidentally deleted the other branch, so that's why this one.
=> move inventory lists

RetrieveExport.md
Adjusting the URI to match the API package structure.
=> Adjusting the URI

Product--ItemDetails.md, Product--SKU_autocomplete.md
=> image -> product_image and kill price_scheme layer

Product--SearchCatalog-SubCatalog_and_Inventory.md
Now that I have completed the roundtrip loop for catalog search, here are my proposed changes.  Most of the data is still intact (some will need to be added back in) but this is now a close representation (~95%) of what I am actually accepting and returning.
Note that the filter that would allow searching catalog or inventory list by uuid is not yet functional (it's like 5 minutes of work at this point to add it in, though).
=> changes to catalog search

Product--SearchCatalog-SubCatalog_and_Inventory.md
Amend the Product--SearchCatalog-SubCatalog_and_Inventory per discussion between John, Nick and Jason.
=> Amend Product Search Catalog 

Product--SearchCatalog-SubCatalog_and_Inventory.md
Add search_term to response
Per conversation with John, search_term will be provided in the response
=> Add search_term to response

Order--RetailerExportFormat.md, Order--RetailerImportFormat.md, Order--SupplierExportFormat.md, Order--SupplierImportFormat.md
=> adding import/export formats for orders

Product--READ-InventoryList-SubCatalog.md
We cut some things that weren't going to be ready on time.
=> Change to reflect MVP excisions

Product--Remove_From_Inventory.md
I'm open to changing these back to uuid, but for now this is how they are implemented.
Should fix https://github.com/DobaTech/thanos/issues/359
=> make add/remove body the same

Notifications.md, Order--AddTracking.md, Order--Allocate.md, Order--Create.md, Order--Detail.md, Order--Export.md, Order--Fees.md, Order--Search.md, Order--SupplierOrders.md, Order--SupplierPickList.md, Product--Add_To_Inventory.md, Product--CREATE-InventoryList-SubCatalog.md, Product--DELETE-InventoryList-SubCatalog.md, Product--Export.md, Product--READ-InventoryList-SubCatalog.md, Product--Remove_From_Inventory.md, Product--SKU_autocomplete.md, Product--UPDATE-InventoryList-SubCatalog.md, RetrieveExport.md
Change the formating of the blocks from ```json to ```js to remove the red highlighting
Github issue 194 (not closed by this pr)
=> Update formatting from json to js

_organization/get_connections.md
Change the name 'relationship' to 'connection' and make sure it is
coherent.
TECHOPS-998
=> Update the name from Relationship to Connection

_ordering/get_order_list.md
Reverts DobaTech/thanos-api-docs#60
=> Revert "Update the order search endpoint for statuses"

PROPOSAL/create_payment_method.md
What do you think of this Jason?  The URI is final, but how about the parameter rename???
=> adds URI and renames parameter to more explicit

PROPOSAL/get_payment_methods.md, PROPOSAL/verify_bank_account.md
I laid all the other fields/endpoints to handle both credit cards and ACH,
but I forgot about ACH verification.
=>  Add fields/endpoint to handle ACH verification

PROPOSAL/update_payment_method.md
How's this for a URL and responses?
=> adds url and responses

PROPOSAL/set_default_payment_method.md, PROPOSAL/update_payment_method.md
Notice the method change
PUT update payment method
PATCH set default payment method.
=> adds set def payment method, updates method change

PROPOSAL/delete_payment_method.md
same path as the others, just DELETE
=> path and responses for delete payment method

_includes/timp/product/response/product_identifiers.md, _includes/v1/product/response/product_identifiers.md
simple fix to upca
cc @konanholt
=> upca is 12 digits, not 11

_fs_order_data/orders.md, _fs_order_data/tracking.md
https://github.com/CruxConnect/crux-docs/issues/210
Updated Tracking document to reflect changes made to the xlsx, and csv file samples.
=> Tracking file update

_order/get_order_fees.md, _order/update_order_attributes.md, _order/update_order_fees.md
While testing a CSV mapper, I noticed that some of the documentation was
incorrect on the fees and attributes endpoints. This will shore up those
few things I found while undoubtedly leaving many errors unfound :/
=> Fix incorrect documentation on fees/attributes

_fs_order_data/allocation.md, _fs_order_data/invoice.md, _fs_order_data/orders.md, _fs_order_data/tracking.md
=> Updated Required Stuff
